version: '2'
services:
  tme-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/tme/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tme
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
